version: "3"  

tasks:
  default:
    cmds:
      - task: server

  server:
    desc: "Start metric server"
    cmds:
      - go run ./cmd/server/main.go {{.CLI_ARGS}}

  agent:
    desc: "Start agent"
    cmds:
      - go run ./cmd/agent/main.go {{.CLI_ARGS}}

  build:
    desc: "Build binaries"
    cmds:
      - go build -o ./cmd/server/server ./cmd/server/main.go
      - go build -o ./cmd/agent/agent ./cmd/agent/main.go
      - go build -o ./cmd/staticlint ./cmd/staticlint/main.go

  clear:
    desc: "Clear building artifacts"
    cmds:
      - rm ./cmd/server/server ./cmd/agent/agent

  mockgen:
    cmds:
      - mockgen -destination=internal/storage/mocks/mock_storage.go -package=mocks github.com/nbvehbq/go-metrics-harvester/internal/server Repository 

  prof:
    cmds:
      - curl -s -v 'http://localhost:8080/debug/pprof/profile?seconds=60' > ./profiles/result.pprof
  
  test:
    cmds:
      - go test ./... coverprofile cover.out && go tool cover -func cover.out && go tool cover -html=cover.out

  lint:
    cmds:
      - go run ./cmd/staticlint/main.go ./...